id: I833F31AA
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T11:08:04+00:00'
last_modified: '2022-06-08T09:26:23.233151+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG10153
  title: ཆོས་སྤྱོད་ཀྱི་རིམ་པ་རྣམ་པར་གྲོལ་བའི་ལམ་གྱི་ཤིང་རྟ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    B616:
      image_group_id: I1KG11893
      title: ''
      total_pages: 668
      order: 1
      base_file: B616.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
