id: P006898
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 12:29:28.188279
source_metadata:
  id: bdr:W1KG10153
  title: ཆོས་སྤྱོད་ཀྱི་རིམ་པ་རྣམ་པར་གྲོལ་བའི་ལམ་གྱི་ཤིང་རྟ།
  author: ''
  volumes:
    25a99e7fad8d424cb8dc4d8027acdf20:
      image_group_id: I1KG11893
      title: ''
      volume_number: 1
      total_pages: 668
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
