id: P006898
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG10153
  title: ཆོས་སྤྱོད་ཀྱི་རིམ་པ་རྣམ་པར་གྲོལ་བའི་ལམ་གྱི་ཤིང་རྟ།
  author: ''
  volumes:
    25a99e7fad8d424cb8dc4d8027acdf20:
      image_group_id: I1KG11893
      title: ''
      volume_number: 1
      total_pages: 668
